services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cashflow_app
    expose:
      - "5000"
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./staticfiles:/cashflowmanage/staticfiles
      - ./media:/cashflowmanage/media
    depends_on:
      - db
    networks:
      - cashflow_network

  db:
    image: postgres:16
    container_name: cashflow_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5435:5432"
    networks:
      - cashflow_network


networks:
  cashflow_network:
    driver: bridge

volumes:
  postgres_data: